### ISSUE TITLE
Function async flush metadata, return 0 is missing

### ISSUE THREAD

**Issue by beef9999** [Open-CAS/ocf#375]
![image](https://user-images.githubusercontent.com/4076315/83620546-0a19fa80-a5c0-11ea-80b2-5b6bd806d855.png)

_ocf_write_wb_io_flush_metadata is invoked twice.

**Comment by robertbaldyga** [comment]
That's because the final call of `_ocf_write_wb_io_flush_metadata()` is required to ensure that completion completion is called after all the ios complete. Notice that the `req->req_remaining` is initially set to 1, but `_ocf_write_wb_io_flush_metadata()` calls completion callback only when `req->req_remaining` drops to 0. That prevents calling completion callback before `ocf_metadta_flush_do_async()` submits all the ios, before some of them may complete immediately, decreasing `req->req_remaining` to initial value. This is quite common pattern.
