### ISSUE TITLE
env_strncpy misbehaves when strlen(src) == strlen

### ISSUE THREAD

**Issue by mgerdts** [Open-CAS/ocf#379]
From code inspection, I found that `env/postix/ocf_env.h` isn't quite right.

```c
#include <stdio.h>
#include <string.h>

#define min(a, b) ((a < b) ? (a) : (b))
#define env_strncpy(dest, dmax, src, slen) ({ \
                strncpy(dest, src, min(dmax - 1, slen)); \
                dest[dmax - 1] = '\0'; \
                0; \
        })

int
main(void)
{
        char buf[16] = "0123456789abcde";
        char *s = "###";

        (void) printf(" before: '%s'\n", buf);
        env_strncpy(buf, sizeof (buf), s, strlen(s));
        (void) printf("  after: '%s'\n", buf);
        return (0);
}
```

```
$ ./t
 before: '0123456789abcde'
  after: '###3456789abcde'
```

My example program is fixed with the following:

```
@@ -4,7 +4,7 @@
 #define min(a, b) ((a < b) ? (a) : (b))
 #define env_strncpy(dest, dmax, src, slen) ({ \
                 strncpy(dest, src, min(dmax - 1, slen)); \
-                dest[dmax - 1] = '\0'; \
+                dest[min(dmax - 1, slen)] = '\0'; \
                 0; \
         })
```

I believe a similar issue exists with `env_strncmp()`, but I have not analyzed callers to understand their intent.

**Comment by Ostrokrzew** [comment]
This is correct behavior.
This solution is based on the *safeclib* library that says 
> If no null character was copied from src, then dest[n] is set to a null character.
In our code, we sets `dest[n-1]` to a null character.
In your example, `strlen(s)` returns 3 because this function doesn't count a terminal character.
You could use your own solution or add 1 to the result of `strlen(s)` to count the null character.
It is also safer to use the `strnlen` function or our wrapper `env_strnlen` (which also doesn't count a terminal character).
