### ISSUE TITLE
Question on Performance of OCF

### ISSUE THREAD

**Issue by sherlockwu** [Open-CAS/ocf#402]
Hi there,

I have a question related to the OCF codebase performance/ scalability. (not related to cache behaviors)

Specifically, Im using some simple code to evaluate OCF's performance. The context logic is same as the example context, except:
1) we do nothing in volume's submit_io function: the example is doing memcpy, while we directly call io->end()
2) we use multiple threads to do ocf_core_submit_io: we change the example's main.c/perform_workload() to be a multi-threaded version
3) miss ratio = 0%

However when we experiment with different number of threads, OCF looks like not scalable, e.g.:
1 thread: 700K requests/s
2 threads: 500K requests/s
4 threads: 360K requests/s

Im wondering: 
1) is this expected?
2) is there any suggestion on configuring a scalable cache? (e.g. should there be some partitions?)

Thanks,
Kan

**Comment by robertbaldyga** [comment]
Hi Kan,

The example is very simplistic and definitely not designed for performance. It's rather as a basic API use case.
This kind of performance drop is not expected and we do not observe it in real life deployments. I think there must be bottleneck somewhere in example implementation or in posix env. Did you perform any profiling in order to identify the bottleneck?

Regards,
Robert

**Comment by katlapinka** [comment]
I'm closing this issue due to no response after long time. 
If it it still a problem, please reopen.
