### ISSUE TITLE
manual eviction

### ISSUE THREAD

**Issue by tconrado** [Open-CAS/ocf#407]
In some scenarios, we can know ahead that a high usage of the cache will be required.
Hence, in this situation, would be very interesting the capability to trigger the eviction in the same way the flush can be triggered.
With that, high performance can be achieved. We suggest a command to evict up a cache percentage defined by while casting the command.

**Comment by robertbaldyga** [comment]
Eviction of clean data is by design pretty cheap (and there are also eviction performance improvements coming in the next major release), so the feature you are looking for is manual cache flushing, which is currently available to some extent with `casadm -F` command. It's not currently possible to choose how much data is to be flushed (flushing is done till 100% of data is clean, but operation can be manually interrupted at any moment). So there definitely is a room for improvement, and we are currently considering adding such feature. Thanks for your insight!

**Comment by mmichal10** [comment]
Hi @tconrado,

our cli utility provides commands which may be suitable for your use case.  `casadm --script --purge-cache --cache-id <cache-id>` invalidates all the data from a particular cache and  `casadm --script --purge-cache --cache-id <cache-id> --core-id <core-id> `  invalidates all the data from one core from the cache instance. 

> We suggest a command to evict up a cache percentage defined by while casting the command
Implementing such a command would require a lot of effort, however we can extend the existing one so user would have a possibility to specify ioclass id which should be invalidated. Let us know if you find such a scenario useful.
