### ISSUE TITLE
How to control the speed of flushing in cleaning-alru policy?

### ISSUE THREAD

**Issue by hertz1987** [Open-CAS/ocf#420]
I wanted to use cleaning-alru policy and achieve the following goals:
- The cleaning thread should wake up every 30s
- Every time the cleaning thread wakes up, it should flush maximum of 40MiB data

The cache line size was 8KB so I thought the flush_max_buffers should be 40 * 1024 / 8 which is 5120
so I set the cleaning-alru policy with the following command:

> casadm -X -n cleaning-alru -i 1 -w 30 -b 5120 -s 120

and then I dd-ed about 1GB data into /dev/cas1-1

But it turned out that after the cleaning thread woke up, instead of flushing 40MiB every 30 seconds, it flushed the whole 1GB data in nearly 14 seconds, so:
1. How does this option work?
2. How can I control the speed of flushing?

**Comment by hertz1987** [comment]
There are scenarios in which I want to limit the flushing speed so that it doesn't affect random reads and sequential reads from the core devices caused by read misses.
I want to be able to limit the flushing speed by specifying IOPS or MBPS or IOs/MBs over a period of time, but it seemed right now there isn't such a way for me to achieve this goal. Any explanation or comment or suggestion would be appreciated!

**Comment by robertbaldyga** [comment]
The way ALRU cleaning works is that it activates only during idle time, when no IO is being submitted for certain amount of time (determined by _activity threshold_ parameter) and no write request has been submitted for _staleness time_. Then it cleans _flush max buffers_ number of cache lines and checks again if cache is still idle, and if it is - it cleans another portion of cache lines immediately, and it repeats until all cache lines are clean. But once IO workload starts, cleaning thread stops and it waits until cache becomes idle again.

In your case after `dd` finished there were no other IO workload, so cache has been idle until all the cache lines have been cleaned. However if there were some IO workload started during the cleaning, the cleaning thread would stop, so that it would not affect your workload.
