### ISSUE TITLE
Removing one core device will cause too long I/O downtime for other devices. 

### ISSUE THREAD

**Issue by YamboZhou** [Open-CAS/ocf#421]
Hi,

We are meeting this issue in the real world deployment:

If one core device is removing, ocf will hold a global metadata lock. In this situation, all the other core devices that are sending I/O to cache will be hanging.  We noticed that though others deivces use different I/O threads, they share the same gloabl lock for metadata. Hence, all the other devices need to wait the lock. 

The following code is pretty time-consuming, so the I/O downtime of other devices are too long. 

while (retry) {

             retry = 0;

             if (cleaning_policy_ops[clean_pol_type].purge_range) {

                    retry = cleaning_policy_ops[clean_pol_type].purge_range(cache,

                                 core_id, 0, core_size);

             }

 

             if (!retry) {

                    /* Remove from collision_table and Partition. Put in FREELIST */

                    retry = ocf_metadata_sparse_range(cache, core_id, 0,

                                 core_size);

             }

 

             if (retry) {

                    ocf_metadata_end_exclusive_access(&cache->metadata.lock);

                    env_msleep(100);

                    ocf_metadata_start_exclusive_access(

                                 &cache->metadata.lock);

             }

       }

There are two stretegies that may address this issue. Could you please help review whether they make sense?

1、dynamic scheduling:
when cleaning cache line and metadata, we could clean up serveral cache lines per 100ms insead of cleaning all cache line. With this shceduling, we could avoid waiting a long time for other devices. 

2、trim data instead of cleaning up cachce line
Whenever ocf removes core device, we could send a discard I/O for this device. Afther that, we could remove this core device without cleaning up related data and metadata. 

Besides, I am wondering whether ocf community has a long-term plan to support fine-grained metadata lock for ocf?

Thanks
Yanbo

**Comment by arutk** [comment]
Hi @YamboZhou,

Sorry it took us so long to respond. What you describe looks like an issue we would definitely like to address in near future.

Before I comment on the two solutions proposed by you, I would like to make sure we're on the same page regarding what's happening on your systems during core removal. I assume you are using CAS Linux. The piece of code which you refer to is part of "ocf_mngt_cache_detach_core" execution. At this point all cachelines mapped to removed core should already be clean. The logic for this is outside OCF, in CAS Linux adapter. So the code which you reference does not actually clean anything, it just updates metadata for all cachelines associated with removed core.  

Regarding your propositions. The second one does not address the problem at all, since discarding the data would require the same metadata update in OCF. The first one would alleviate the problem somewhat, but I think it does not address the source of the problem: the fact that removing core acquires global metadata exclusive lock for an extended period of time.

In my opinion the way to approach this problem is to get rid of global metadata lock in this peace of code and perform metadata updates iteratively, walking through all the hash buckets assiciated with removed core and locking them one by one using ocf_metadata_hash_lock with OCF_METADATA_WR. This would involve logic similar to ocf_engine_lookup_map_entry to iterate for all cachelines assiciated with hash bucket:

for (hash = 0; hash < _NUM_HASH_ENTRIES; hash++) {
	ocf_metadata_hash_lock(&cache->metadata.lock, hash, OCF_METADATA_WR);  
	line = hash;
	while (line != cache->device->collision_table_entries) {
                ocf_metadata_get_core_info(cache, line, &curr_core_id,
                                &curr_core_line);

		if (curr_core_id == <core being removed) {
			// update metadata for single cache line @line
		}
		
		line = ocf_metadata_get_collision_next(cache, line);
	}
	ocf_metadata_hash_unlock(&cache->metadata.lock, hash, OCF_METADATA_WR);
}

Regarding your last question. Indeed we are working on a fine-grained metadata locking in CAS. In fact there already is a fine-grained lock (the hash bucket lock ocf_metadata_hash_lock ). However there are still some cases where we acquire global metadata lock, which is exclusive with the fine-grained hash bucket lock. Currently we acquire the global exclusive lock for  eviction (I/O service path) and management operations (like removing the cores). The top priority for us us to remove the global metadata lock from I/O path. We plan to have it done for 20.12 in January next year. After this we will try to address the problem which you describe, although I can't tell now when we have resources to do this.

**Comment by YamboZhou** [comment]
Thanks @arutk 

We already talked with @michalwy in meeting last week. As you said, Michal also suggested us using fine-grained metadata lock in your incoming release. 

In our situation, we use our private software architecture instead of CAS Linux and SPDK.  This is similar to SPDK VHOST. We use dedicated CPU cores for polling-mode driver and a global core for control planes, e.g., remove core, add core, etc. 

We plan to use the first approach as a temporary  solution and wait to your formal release.

Thanks!
