### ISSUE TITLE
A data race error on the shared variable treq->finished (CWE-362)

### ISSUE THREAD

**Issue by anson-lo** [Open-CAS/ocf#542]
Dear developers, thank you for your checking! The function `req_lock_sync` may be executed concurrently and the shared variable `treq->finished=false` may not be protected correctly by the lock, which can lead to a data race. I check other places that use `treq->finished` and it is all protected by the lock. Should it be a bug? I am looking forward to the discussion.

https://github.com/Open-CAS/ocf/blob/73c3e97f43b482ed8162d18314054a0b5d4b5d69/tests/unit/tests/concurrency/ocf_cache_line_concurrency.c/ocf_cache_line_concurrency.c#L279

```
bool req_lock_sync(struct ocf_cache_line_concurrency *c, struct ocf_request *req,
		int (*pfn)(struct ocf_cache_line_concurrency *c, struct ocf_request *req,
				void (*cmpl)(struct ocf_request *req)),
		volatile int *finish)
{
	...;
	treq->finished = false; // without being protected by the lock, the fix is to add lock here

	...;

	pthread_mutex_lock(&treq->completion_mutex);
	while (!treq->finished && !*finish) {  // protected
		pthread_cond_wait(&treq->completion,
			&treq->completion_mutex);
	}
	pthread_mutex_unlock(&treq->completion_mutex);

	return treq->finished;
}
```

```
static void req_async_lock_callback(struct ocf_request *req)
{
	...;
	pthread_mutex_lock(&treq->completion_mutex);
	treq->finished = true;  // protected
	pthread_cond_signal(&treq->completion);
	pthread_mutex_unlock(&treq->completion_mutex);
}
```

Best,

**Comment by mmkayPL** [comment]
Doesn't look like a bug - for a given test_req this unprotected setting of finished flag is initialization without any concurrency going on. Concurrency may begin during/after the pfn call in the next line.

**Comment by anson-lo** [comment]
@mmkayPL Thank you for your reply.

The entire `req_lock_sync()` is called in the threaded function `thread(void *_ctx)` and is also in `while ` loop. It seems the concurrency has already started?

**Comment by mmkayPL** [comment]
There are multiple threads running, but each thread is responsible for it's own test_req and this exact part of the code won't be executed in parallel. The execution looks like the following from a single thread's point of view:

1. It initializes finished to false
2. It executes pfn (which is either ocf_req_async_lock_wr or ocf_req_async_lock_rd)
3. If there was no contention on the cacheline, the lock was acquired synchronously and nothing more happens (this is line 284)
4. However if the cacheline was already locked by another thread B, then we need to wait for the completion. due to OCF design this completion will be called from the context of thread B, once it's done with its lock. This is why the mutex needs to exist for line 288.
5. The test is waiting synchronously for this completion (the while loop at line 289; there's only one completion per request, though technically there's no check for this here), so once it's done it's safe to go back to point 1 in the next iteration of the loop, since noone else will be touching it in the meantime

**Comment by anson-lo** [comment]
@mmkayPL  Thank you very very much for your detailed reply! My problem is solved now.

**Comment by anson-lo** [comment]
@mmkayPL  Thank you very very much for your detailed reply! My problem is solved now.

**Comment by anson-lo** [comment]
@mmkayPL  Thank you very very much for your detailed reply! My problem is solved now.
