### ISSUE TITLE
Failed to understand some parameters

### ISSUE THREAD

**Issue by USTCqzy** [Open-CAS/ocf#558]
## Question
Failed to understand some parameters.
In `inc/ocf_mngt.h`
```c
/**
 * @brief Initialize core config to default values
 *
 * @note This function doesn't initialize name field which has no default
 *       value and is required to be set by user.
 *
 * @param[in] cfg Cache config stucture
 */
static inline void ocf_mngt_cache_config_set_default(
		struct ocf_mngt_cache_config *cfg)
{
	cfg->cache_mode = ocf_cache_mode_default;
	cfg->promotion_policy = ocf_promotion_default;
	cfg->cache_line_size = ocf_cache_line_size_4;
	cfg->metadata_layout = ocf_metadata_layout_default;
	cfg->metadata_volatile = false;
	cfg->backfill.max_queue_size = 65536;
	cfg->backfill.queue_unblock_size = 60000;
	cfg->locked = false;
	cfg->pt_unaligned_io = false;
	cfg->use_submit_io_fast = false;
}
```
How does `metadata_layout` make difference in performance?
What does `metadata_volatile` mean?
Is `pt_unaligned_io` or `use_submit_io_fast` kind of an optimization option? How does `submit_io_fast` work?
```c
static inline void ocf_mngt_core_config_set_default(
		struct ocf_mngt_core_config *cfg)
{
	cfg->try_add = false;
	cfg->seq_cutoff_threshold = 1024;
	cfg->seq_cutoff_promotion_count = 8;
	cfg->user_metadata.data = NULL;
	cfg->user_metadata.size = 0;
}
```
What does `seq_cutoff_threshold ` & `seq_cutoff_promotion_count ` mean?

I also found an idea of `io class`, which seems no appearance in open cas homepage.
```c
/**
 * @brief IO class configuration
 */
struct ocf_mngt_io_class_config {
	/**
	 * @brief IO class ID
	 */
	uint32_t class_id;

	/**
	 * @brief IO class maximum size
	 */
	uint32_t max_size;

	/**
	 * @brief IO class name
	 */
	const char *name;

	/**
	 * @brief IO class cache mode
	 */
	ocf_cache_mode_t cache_mode;

	/**
	 * @brief IO class eviction priority
	 */
	int16_t prio;
};
```

As a new comer, it really takes me much time to figure out all kinds of things, and questions above are unsolved and kind of hard for me. If you can provide some explainations, I might make rapid progress.

## Motivation
Actually, I am interested in params other than the obvious ones, and believe they also matter.

## Your Environment
SPDK version: 21.07.x
OCF version (commit hash or tag): 05401ca (fit SPDK version)
Operating System: Ubuntu 20.04

**Comment by rafalste** [comment]
Hi @USTCqzy,
sorry for the delay in responding. I've delegated your questions to one of our more experienced engineer, as he will be able to explain those parameters in a way that can be easily understood.
I just need to ask you for a bit more patience, as we have a lot on our plate right now.

In the meantime, you can take a look at our [Open CAS documentation](https://open-cas.github.io/). There you can find at least some info about IO classes. :)

**Comment by arutk** [comment]
Hi @USTCqzy. 

Answering your questions:
1. Metadata layout (striping vs sequential) affects the order of metadata entries - most importantly the order of "collision" entries, where cacheline mapping and dirty status are stored. 

With sequential layout metadata for two cachelines that are adjacent on the cache drive is stored back-to-back as well. For example data for cachelines 0 and 1 is stored next to each other on the cache drive, at the beginning of the data section (right after the metadata). Collision metadata for these two cachelines is then located also at the beginning of collision metadata array, at indexes 0 and 1 respectively.

With striping on other hand metadata for cachelines 0 and 1 (physical domain, meaning the offset of the data on cache drive) is split so that corresponding metadata is stored on distant indexes. Considering the example above, cachelines 0 and 1 (physical domain) would translate to something similar to index 0 and 301 in the collision array respectively (this is what is reffered to as cacheline number or logical cacheline number in OCF).

Striping is designed to avoid mapping two subsequent I/Os to similar cachelines (logical). We want to avoid this because collision metadata is often flushed from RAM to the drive during I/O servicing. Collision metadata for adjecent logical cachelines reside in the same disk page. If two concurrent I/Os flush the same collision metadata page then they need to serialize their I/O to the cache drive (it is required to maintain data integrity in case of power failure). Also historically SSDs had trouble with repeated writes to the same address, although this is a thing of the past now.

Striping should affect performance mostly during inserting to empty cache, when subsequent physical cachelines are assigned to subsequent cache misses. Performance impact might persist longer after the cache is filled depending on I/O pattern.

2. Volatile metadata is not written to the cache drive. Entire cache drive is used to store data only and metadata lives in RAM only. After stopping cache or system restart there is no way to load the cache and dirty data is lost, as there is no way to restore cacheline status or the mapping between primary storage LBA's and cache drive adresses (physical cacheline number).

3. pt_unaligned_io controlls whether an I/O not aligned to 4K should be handled normally or sent in pass-through.

4. use_submit_io_fast  was used with older kernels (before 5.8). We used to have this logic where in WB mode we attempted to service cache hits from kernel "request_fn" callback ("bio interface") - this is what ocf_submit_io_fast() entry point was used to. It checks whether a request is a hit and cache mode is WB/WO. In this case the I/O is serviced, otherwise negative status is returned. In case of negative status (meaning I/O was not handled), we then requested kernel I/O scheduler to re-submit I/O via the standard API (the "request interface"). When "use_submit_io_fast" is set to false OCF never handles I/O in submit_io_fast().
So overall this entry point is very specific to how our integration with linux kernel adapter used to work, we will probably remove this entry point entirely soon.

I will follow up about sequential cutoff promotion/cutoff thresholds in the next message.

Adam

**Comment by arutk** [comment]
Sequential cutoff is a mechanism used to bypass cache for sequential I/Os. The idea is that sequential I/O is typically rare, one-time maintenance operation (like ceph scrubbing) and inserting cachelines is in this case a waste of cache space (cache pollution).

sequential_cutoff_threshold controlls how much sequential data needs to be detected in order to start bypasing the cache (sending OCF I/Os in pass-through). For example when set to 1MiB, the following will happen:
  - user writes 512KiB to adress X - OCF services write as usual
  - user writes 512KiB to adress X + 512KiB - OCF services write as usual
  - user writes 512KiB to adress X + 1024KiB - OCF handles I/O in pass-through.

For performance reasons internal sequential cutoff structures are duplicated, with a set of per-CPU versions and one global instance. The purpose is to reduce number of modifications of the global structure. Until a number of subsequent sequential I/Os does not reach sequential_cutoff_promotion_count the information about the sequential stream is stored only in per-cpu structures. As a result if the thread submitting a sequential I/O stream is rescheduled to a different CPU before it wrote sequential_cutoff_promotion_count I/Os, the tracking for this stream is basically lost. After reaching sequential_cutoff_promotion_count  local stream is promoted to the global structure and all CPUs will be able to detect continuation of this stream. As a summary, promotion mechanism allows you to improve performance at the cost of potentially not detecting some portion of sequential streams in case of thread migration to another CPU. 

The two sequential cutoff parameters are independent of each other. sequential_cutoff_threshold is specifying when to send sequential data in PT. sequential_cutoff_promotion_count allows you to tune the balance between performance and sequential stream detection accuracy. Note that setting sequential_cutoff_promotion_threshold to 0 basically disables the promotion mechanism, as everything is tracked in a global structure. This gives you best accuracy, but limits OCF throughput at below 1M IOPS vs around 2.5M with default promotion count settings (random reads, 100% hit).

**Comment by arutk** [comment]
IO classes allow user to partition the cache and define eviction priority of each partition (the higher the eviction priority the more likely cachelines within given partition will get evicted). OCF IO submit interface accepts IO class parameter - this defines to which IO class will the cachelines hit / inserted by this I/O be assigned. It is up to the layer above OCF to decide on the IO class for each I/O, typically by differentiating between I/Os of different priority or expected lifetime.

'cache_mode' parameter of ocf_mngt_io_class_config is not implemented :/.

I/O class priorities are explained on Open CAs Linux manual here:
https://open-cas.github.io/guide_io_classification.html
Note that classification rules (IO class name syntax) described in the admin guide above are specific to Open CAS Linux adapter, so this part is not included in OCF.

**Comment by beef9999** [comment]
> The idea is that sequential I/O is typically rare

A little suspicious about that. Could you elaborate?

**Comment by arutk** [comment]
Hi @beef9999. Sure, let me clarify. In our experience large (above 1MiB) sequential I/O typically contains relatively cold data, meaning it won't likely be accessed again soon. If this assumption is correct, inserting the data to cache is just polluting it.

Another argument for cutting of large sequential I/O is that typically core devices (primary storage) handles sequential I/O well, so the benefit of caching this data is relatively low even if it isn't that cold.

This depends on the workload of course. If it doesn't fit your workload, you can always disable sequential cutoff or set a higher cutoff threshold.
